Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift
Tests/CodableDatastoreTests/SnapshotTests.swift

Updated the back-reference from a snapshot to a persistence to be unowned instead of weak.

Unowned Back References

---

Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Sources/CodableDatastore/Persistence/Memory Persistence/MemoryPersistence.swift
Sources/CodableDatastore/Persistence/Persistence.swift

Added new method to Persistence for loading a datastore descriptor at any time.

On Demand Datastore Descriptors

---

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePageEntry.swift
Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistenceError.swift
Tests/CodableDatastoreTests/DatastorePageEntryTests.swift

Fixed an issue decoding partial entries when the header could be incomplete.

DatastorePageEntry Decoding Tests

---

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndexManifest.swift

Improve performance writing to the datastore by 2× at 10k writes, though it is still exponential in some way due to the filter.

Don't Be Lazy

---

Sources/CodableDatastore/Persistence/TransactionOptions.swift
Tests/CodableDatastoreTests/TransactionOptionsTests.swift

Added unsafe transaction options, including one to skip observations.

Unsafe Transaction Options

---

Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/SnapshotManifest.swift

Fixed an issue where multiple datastores could be created before the first write to a persistence.

Persistence Datastore Actor Durability

---

Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift
Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift

Fixed an issue where the datastore root would be lost when loading a persistence from disk.

Load From Disk

---

Sources/CodableDatastore/Datastore/Datastore.swift
Sources/CodableDatastore/Datastore/Dictionary+RawRepresentable.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift
Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift

Refactored RawRepresentable access within Codable Dictionaries with String keys.

RawRepresentable Dictionary Access

---

README.md
Sources/CodableDatastore/Datastore/Dictionary+RawRepresentable.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift

Added disk persistence support for removing indexes.

Removing Indexes

---

README.md
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePage.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift
Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift

Updated Disk Persistence to use a cache instead of keeping all objects in memory indefinitely.
https://github.com/mochidev/CodableDatastore/assets/225505/f6d4e824-139e-4b5a-b3ee-8f5c5fdc8bcd
https://github.com/mochidev/CodableDatastore/assets/225505/8678eeef-edfd-4138-a85c-28692f78beff

Memory Efficiency

---

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift
Tests/CodableDatastoreTests/DiskPersistenceDatastoreIndexTests.swift

Fixed an issue where the incorrect cursor may be returned when the next entry spans multiple pages.

Broken Insertion Cursor

---

Sources/CodableDatastore/Datastore/Datastore.swift

Updated Identifiable instance accessors to be disfavored in cases where their IDs were similarly shaped. ie. the coded type is an enum, with the same members in the ID type.

Disfavored Accessors

---

Sources/CodableDatastore/Datastore/Datastore.swift

Updated persist methods to return previous values when updating older instances.
Fixed #180

Return Replaced Values

---

README.md
Sources/CodableDatastore/Datastore/DatastoreFormat.swift

- Added a more complete DatastoreFormat example.
- Added public typealiases for the Datastore types on the format.
- Fixed an issue where the Identifier type was not marked as public.

Format Fixes

---

Sources/CodableDatastore/Datastore/Datastore.swift

Fixed an issue where migrations involving reference indexes could fail.

Reference Migration Fix

---

Sources/CodableDatastore/Datastore/Datastore.swift
Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift

- Fixed an issue where migrations could be stopped prematurely.
- Added a read step to entry persistence tests to ensure no corruption occurred.

More Migration Fixes

---

Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift

- Fixed a race that could occur where a long running read-only transaction could overwrite writes that just occurred.
- Added assertions to ensure read-only transactions don't process mutations accidentally.

Transaction Race Corruption

---

Sources/CodableDatastore/Indexes/Indexable.swift
Tests/CodableDatastoreTests/OptionalTests.swift

Fixed an issue where optional comparisons would not be ordered correctly.

Optional Index Ordering

---

README.md
Sources/CodableDatastore/Indexes/UUID+Comparable.swift

On packages that target the latest SDKs, Comparable conformance is already present, thus leading to ambiguity. This should hopefully address that when the operator is used directly.

Better UUID Comparable Conformance

---

README.md
Sources/CodableDatastore/Indexes/UUID+Comparable.swift

Added a raw `uuid_t` comparison implementation that's always available.

Raw UUID Comparisons

---

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePage.swift

Fixed an issue where disk file handles for memory cached data were held open indefinitely.

Close Open File Handles When Cached

---

Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift

Fixed a retain cycle that could prevent a DiskPersistence from deinitializing when no longer used.

Disk Persistence Retain Cycle

---

Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift

Lowered maximum transaction object count in memory at once by not keeping every child transaction around until the parent is complete.

Child Transaction Optimization

---

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePageEntry.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Tests/CodableDatastoreTests/DiskPersistenceDatastoreIndexTests.swift

Fixed an issue where secondary index cursor lookups could fail if the contents (ie. the ID) ended split on a page, causing the comparator to fail decoding the entry leading to a failed lookup. This only affected datastores with secondary indexes configured.

Secondary Index Partial Content

---

Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift

Updated missing file handlers to be simpler.

Simplify Missing File Handlers

---

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePage.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRootManifest.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift

Refactored url fetching so it is more centralized, and fixed some old swift syntax along the way.

File URL Refactor

---

Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift

Fixed an issue where extra index manifests were created on certain writes and updates.

Extra Index Manifests

---

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift
Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/SnapshotIteration.swift
Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Tests/CodableDatastoreTests/SnapshotIterationTests.swift

This fixes the iteration chain in two key ways:
- incomplete references to datastore roots that were missing the identifier to the specific datastore.
- missing references between snapshots when a hypothetical new snapshot is taken.

Complete References
