Tests/CodableDatastoreTests/IndexedTests.swift
Added more tests to Indexed to check codable conformance of leaf types.
=> More Codable Tests

Sources/CodableDatastore/CodableDatastore.docc/On Disk Representation.md
Added more documentation for the file format
=> More File Format Specs

Sources/CodableDatastore/Datastore.swift
Added stub methods for observing changes to a data store
=> Observation Stubs

.swiftpm/xcode/xcshareddata/xcschemes/CodableDatastore.xcscheme, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Added more documentation to new StoreInfo accessors
=> Internal StoreInfo Accessor Docs

Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Datastore/DatastoreDescriptor.swift, Sources/CodableDatastore/Indexes/IndexPath.swift, Sources/CodableDatastore/Indexes/Indexed.swift, Tests/CodableDatastoreTests/DatastoreDescriptorTests.swift, Tests/CodableDatastoreTests/IndexedTests.swift
Added new IndexPath type to fix issues with keypaths, specifically that the name on property wrappers would not work.
=> IndexPaths Make Everything Better

Sources/CodableDatastore/Datastore/Datastore.swift
Added persistence and key properties to the datastore.
=> Datastore Persistence Pointer

Sources/CodableDatastore/Datastore/Datastore.swift
Fleshed out migration and warm up interface on Datastore.
=> Warmup and Migration API Surface

Sources/CodableDatastore/Datastore/DatastoreDescriptor.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Sources/CodableDatastore/Persistence/Disk Persistence/JSONCoder.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift
Refactored shared coder implementations that keep getting re-used.
=> Refactored Shared Coders

Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift
Updated withManifest methods to work on any snapshot, not just readonly ones.
=> More Lenient Snapshot.withManifest

Sources/CodableDatastore/Persistence/Disk Persistence/TypedIdentifier.swift, Tests/CodableDatastoreTests/TypedIdentifierTests.swift
Added an initializer to TypedIdentifierProtocol to generate IDs from user data.
=> Named Typed Identifiers

Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/SnapshotManifest.swift, Tests/CodableDatastoreTests/SnapshotTests.swift
Added data store info to Snapshot Manifest.
=> Datastore Info

Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Updated loadSnapshot to not be async or throwing.
=> Sync DiskPersistence.loadSnapshot

Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift
Added datastore loading methods to snapshot.
=> Load Snapshot Datastores

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRootManifest.swift
Added a type to serialize datastore root objects.
=> Datastore Root Serialization

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift
Added root object loading to persistence datastores.
=> Persistence Datastore Roots

Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Updated datasource registration to return the datastore descriptor saved to disk.
=> Registration Descriptors

Sources/CodableDatastore/Datastore/DatastoreDescriptor.swift, Sources/CodableDatastore/Datastore/RawRepresentable+Codable.swift
Added RawRepresentable helper methods for dealing with Codable Versions.
=> RawRepresentable Codable Helpers

Sources/CodableDatastore/Datastore/Progress.swift
Added Progress type for simple progress reporting.
=> Progress Helpers

Sources/CodableDatastore/Datastore/Datastore.swift
Added starting implementation to migration and warmup methods.
=> Incomplete Migration Implementation

Sources/CodableDatastore/Datastore/Datastore.swift
Updated observation event names.
=> Observation Event Names

Sources/CodableDatastore/Datastore/Datastore.swift
Cleaned up the Datastore file and added markers.
=> Datastore Markers and Cleanup

Sources/CodableDatastore/Persistence/Disk Persistence/JSONCoder.swift
Updated JSON coders to pretty print when run in debug mode.
=> Pretty Printed JSON

Sources/CodableDatastore/Datastore/Datastore.swift
Updated progress handlers to use nil to avoid closure callbacks if we don't need to make any.
=> Nil Progress Handlers

Sources/CodableDatastore/Datastore/Datastore.swift
Added and initialized instance properties to Datastore.
=> Datastore Instance Properties

Sources/CodableDatastore/CodableDatastore.docc/On Disk Representation.md, Sources/CodableDatastore/Datastore/DatastoreDescriptor.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Sources/CodableDatastore/Persistence/Memory Persistence/MemoryPersistence.swift, Sources/CodableDatastore/Persistence/Persistence.swift
Added entry manipulation methods to _Persistence protocol.
=> Entry Manipulation

Sources/CodableDatastore/Datastore/DatastoreDescriptor.swift, Sources/CodableDatastore/Indexes/IndexPath.swift, Tests/CodableDatastoreTests/DatastoreDescriptorTests.swift
Added slightly easier to pull IndexPaths.
=> IndexPath Accessors

Sources/CodableDatastore/Datastore/DatastoreDescriptor.swift, Sources/CodableDatastore/Indexes/Mirror+Indexed.swift
Refactored CodedType reflection as a static method on Mirror.
=> Codable Index Reflection

Sources/CodableDatastore/Persistence/Persistence.swift, Sources/CodableDatastore/Persistence/PersistenceError.swift
Added Persistence errors for fetching instances.
=> Instance Lookup Errors

Sources/CodableDatastore/Datastore/DatastoreDescriptor.swift
Fixed typos in DatastoreDescriptor documentation.
=> Documentation Typos

Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Datastore/DatastoreError.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Sources/CodableDatastore/Persistence/Memory Persistence/MemoryPersistence.swift, Sources/CodableDatastore/Persistence/Persistence.swift
Added implementation to persist datastore method.
=> Datastore Write Frontend

Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Sources/CodableDatastore/Persistence/Memory Persistence/MemoryPersistence.swift, Sources/CodableDatastore/Persistence/Persistence.swift, Sources/CodableDatastore/Persistence/TransactionOptions.swift
Added transaction options for performing a batch of changes.
=> Transaction Options

Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Added first pass at some transaction types.
=> Transactions

Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
=> watchOS Compatibility

Package.swift
Removed temporary support for Swift 5.6.
=> Minimum Swift 5.7

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift
Added placeholder type for datastore roots to be managed in memory.
=> Datastore Roots

Sources/CodableDatastore/CodableDatastore.docc/Conceptual/Persisting History.md
Added a conceptual document outlining how history is saved.
=> History Docs

Sources/CodableDatastore/Datastore/Datastore.swift
Added some doc comments for persisting instances in a datastore.
=> Persist Method Docs

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePage.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRootManifest.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift
Added placeholder types for datastore indexes and pages.
=> Index and Page Actors

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePage.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift
Added datastore root object loading to relevant actor.
=> Root Object Loading

.gitignore, Package.swift
Added AsyncSequenceReader and Bytes as dependencies.
=> Added New Dependencies

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndexManifest.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistenceError.swift
Added index manifest loading to relevant actor.
=> Index Manifest Loading

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePage.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift
Cleaned up Index and Page URL handling.
=> Index URL Cleanup

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreEntryBlock.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistenceError.swift
Added support for serializing and deserializing entry blocks.
=> Entry Blocks

Sources/CodableDatastore/CodableDatastore.docc/Conceptual/On Disk Representation.md
Updated the disk representation for the block format.
=> Updated Block Format Docs

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreEntry.swift
Added serialization support for entries into data and blocks.
=> Entry Serialization

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift
Fixed an issue where index manifests could be loaded more than once.
=> Serial Manifest Loading

Package.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndexManifest.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePage.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePageEntryBlock.swift
Simplified some of the parsing paths to use new Bytes check methods.
=> Deserialization Simplification

Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistenceError.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Added a connection between transactions and the roots they keep track of.
=> Transaction Roots

Sources/CodableDatastore/Indexes/UUID+Comparable.swift
Fixed an issue building for visionOS.
=> Add visionOS Support

Sources/CodableDatastore/Persistence/DatastoreInterfaceError.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DatastoreInterface.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Refactored descriptor loading into transaction.
=> Descriptor Loading

Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Datastore/DatastoreKey.swift, Sources/CodableDatastore/Persistence/DatastoreInterfaceProtocol.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DatastoreInterface.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/SnapshotManifest.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Added strongly-typed DatastoreKey.
=> Added DatastoreKey

Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Reintroduced basic transaction support.
=> Transaction Implementation

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePage.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRootManifest.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Added implementation to apply descriptors on a transaction.
=> Apply Descriptors Implementation

Sources/CodableDatastore/Persistence/DatastoreInterfaceError.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistenceError.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Updated transactions to properly persist once complete.
=> Transaction Persistence

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Tests/CodableDatastoreTests/DiskTransactionTests.swift
Fixed an issue persisting data caught by a new test.
=> Apple Descriptor Test

Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Updated persistence to only persist when edits have been made.
=> Write Only When Necessary

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePageEntry.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistenceError.swift, Sources/CodableDatastore/Persistence/Disk Persistence/SortOrder.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/DiskCursor.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Added file-based binary search for locating entries.
=> Binary Search

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePageEntry.swift, Tests/CodableDatastoreTests/DatastorePageEntryTests.swift
Fixed a crash that could occur when assembling blocks from an entry.
=> Entry Decomposition Tests

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreIndexTests.swift
Fixed an issue where page search would not progress past the first page.
=> Page Search Tests

.swiftpm/xcode/xcshareddata/xcbaselines/CodableDatastoreTests.xcbaseline/8A10B1EA-398E-4822-A587-2E59AF1B7EBC.plist, .swiftpm/xcode/xcshareddata/xcbaselines/CodableDatastoreTests.xcbaseline/Info.plist, Tests/CodableDatastoreTests/DiskPersistenceDatastoreIndexTests.swift
Added performance tests for page lookups.
=> Performance Tests

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/DiskCursor.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Added implementation for fetching an insertion cursor from an index.
=> Insertion Cursors

Sources/CodableDatastore/Persistence/DatastoreInterfaceError.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePage.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePageEntryBlock.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/DiskCursor.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift
Added missing pieces to implement basic writing.
=> Basic Writing

README.md
Added project status to the main README.
=> README To Dos

Sources/CodableDatastore/Debug/GlobalTimer.swift
Added a debug type for live-timing ranges of code.
=> Debug GlobalTimer

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/LazyTask.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreIndexTests.swift
Improved page lookup speed by caching and lazy-loading the pages for an index.
=> Page Lookup Speed

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePage.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift
Fixed an issue deduplicating loaded pages as they were incorrectly keyed to an index manifest.
=> Page Index Fix

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Fixed an issue with entry insertion where created pages could be larger than the maximum allowed.
=> Insertion Fixes

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastorePageEntryBlock.swift
Fixed an issue where blocks could not be decoded from disk.
=> Block Decoding Fix

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift
Added an implementation for inserting after an existing entry.
=> Insert After Implementation

Sources/CodableDatastore/Debug/GlobalTimer.swift
Added configurable sample rate to GlobalTimer.
=> GlobalTimer Sample Rate

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndexManifest.swift, Sources/CodableDatastore/Persistence/Disk Persistence/TypedIdentifier.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift
Refactored index page list processing to enable log n insertions.
=> O(log n) Insertions

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift
Improve insertion performance by 1.5× by changing the default page size to 4KB.
=> More Performance Improvements

.swiftpm/xcode/xcshareddata/xcbaselines/CodableDatastoreTests.xcbaseline/8A10B1EA-398E-4822-A587-2E59AF1B7EBC.plist, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreIndexTests.swift
Fixed a regression in page lookup times introduced by using optionals.
=> Page Lookup Regression

Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Fixed an issue where child transactions were not being properly applied to their parent.
=> Working Child Transactions

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift
Improved child transaction performance, leading to a 6× speedup inserting over not using transactions to group inserts.
=> Faster Child Transactions

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift
Updated index mutations to use sets for created pages.
=> Index Cleanup

Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift
Updated transaction tests to time the entire transaction and not just the contents.
=> Transaction Test Timing Fix

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndexManifest.swift
Improved correctness of added and removed pages when child tasks are involved. This preps the way for history to be properly recorded allowing unlimited undo across app launches.
=> Better Page Bookkeeping

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift
Added code to replace and update entries.
=> Replace/Update Entries

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift
Added implementation to delete entries from an index.
=> Delete From Index

Sources/CodableDatastore/Datastore/Datastore.swift
Added implementation for loading entries with a specific ID.
=> Load By ID

README.md
Updated README with finished requirements.
=> README Checklist

Sources/CodableDatastore/Persistence/DatastoreInterfaceError.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift
Added support for indexing values within entries.
=> Indexing Support

README.md, Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift
Added count tracking to the datastore.
=> Datastore Counts

Sources/CodableDatastore/Persistence/Disk Persistence/AsyncThrowingBackpressureStream.swift
Added internal backpressure-aware stream.
=> Backpressure Stream

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift
Added methods to index to scan forwards and backwards given a starting point.
=> Index Scanning

Sources/CodableDatastore/Datastore/TypedAsyncSequence.swift, Sources/CodableDatastore/Persistence/Disk Persistence/AsyncThrowingBackpressureStream.swift
Updated TypedAsyncSequence to live in its own file to make it easier to add more conformances.
=> Typed Sequences

Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Datastore/ObservedEvent.swift
Renamed Observation to ObservedEvent.
=> ObservedEvent

Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Datastore/TypedAsyncSequence.swift, Sources/CodableDatastore/Persistence/DatastoreInterfaceProtocol.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Added ability for observers to register themselves with a persistence.
=> Event Observers

README.md, Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Persistence/DatastoreInterfaceProtocol.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/PersistenceDatastore.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift
Added events to create/update/delete operations that propagate to registered observers.
=> Emit Events to Observers

Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Indexes/IndexRangeExpression.swift, Sources/CodableDatastore/Persistence/DatastoreInterfaceProtocol.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndex.swift, Sources/CodableDatastore/Persistence/Disk Persistence/SortOrder.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift, Tests/CodableDatastoreTests/IndexRangeExpressionTests.swift
Added support for loading ranges of identifiers.
=> Primary Index Ranged Reads

README.md, Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Persistence/DatastoreInterfaceProtocol.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Added ability to read from any index with a range of values.
=> Index Ranged Reads

Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Datastore/DatastoreDescriptor.swift, Sources/CodableDatastore/Indexes/IndexPath.swift, Sources/CodableDatastore/Indexes/Indexed.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift, Tests/CodableDatastoreTests/IndexedTests.swift
Updated IndexPath to surface underlying indexed type.
=> Typed IndexPath

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreIndexManifest.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DatedIdentifier.swift, Tests/CodableDatastoreTests/DatedIdentifierTests.swift, Tests/CodableDatastoreTests/SnapshotTests.swift
Added milliseconds to dated file names for easier debugging.
=> Files with Milliseconds

README.md, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/SnapshotIteration.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/SnapshotManifest.swift, Tests/CodableDatastoreTests/SnapshotTests.swift
Refactored snapshots to operate with multiple iterations.
=> Snapshot Iterations

Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/SnapshotIteration.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift, Sources/CodableDatastore/Persistence/Memory Persistence/MemoryPersistence.swift, Sources/CodableDatastore/Persistence/Persistence.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift, Tests/CodableDatastoreTests/DiskTransactionTests.swift
Added action names to snapshot iterations.
=> Action Names

Sources/CodableDatastore/Persistence/Disk Persistence/DiskPersistence.swift
Updated current snapshot accessors to be less ambiguous.
=> Less Ambiguous Accessors

README.md, Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Datastore/DatastoreError.swift, Sources/CodableDatastore/Persistence/TransactionOptions.swift
Added complete implementation for migrating incompatible indexes during datastore registration.
=> Warmup Migrations

Sources/CodableDatastore/Persistence/Disk Persistence/Snapshot/Snapshot.swift
=> Update loadManifest to use correct url for reopening Datastore

README.md, Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Datastore/DatastoreDescriptor.swift, Sources/CodableDatastore/Indexes/IndexName.swift, Sources/CodableDatastore/Indexes/IndexPath.swift, Sources/CodableDatastore/Indexes/IndexType.swift, Sources/CodableDatastore/Indexes/Indexed.swift, Sources/CodableDatastore/Persistence/DatastoreInterfaceProtocol.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRootManifest.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift, Sources/CodableDatastore/Persistence/Disk Persistence/TypedIdentifier.swift, Tests/CodableDatastoreTests/DatastoreDescriptorTests.swift
Renamed Index key and indexType to typed name and type.
=> Index Name

Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRoot.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Datastore/DatastoreRootManifest.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Renamed IndexInfo.key to .name for consistency.
=> More Index Name

README.md
Updated list of todos for 1.0.
=> Todo Update

Sources/CodableDatastore/Datastore/Datastore.swift
Cleaned up some vestigial type shenanigans.
=> Minor Type Cleanup

Sources/CodableDatastore/Indexes/UUID+Comparable.swift
=> Proper visionOS Support

Sources/CodableDatastore/Datastore/Datastore.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift
Fixed an issue where loading from a fresh datastore would throw an error.
Fixes #163
=> Loads From Fresh Datastores

Sources/CodableDatastore/Datastore/Datastore.swift
Added deletion methods that don't throw for non-existent entries.
=> Delete If Present Mutation Methods

Package.swift, Sources/CodableDatastore/Indexes/IndexRangeExpression.swift, Sources/CodableDatastore/Persistence/Disk Persistence/SortOrder.swift, Sources/CodableDatastore/Persistence/Disk Persistence/Transaction/Transaction.swift
Optimized scanning to skip decoding index entries when iterating over an extent in either direction.
=> Optimized Scanning

Sources/CodableDatastore/Indexes/Indexable.swift
Updated Optional to conditionally conform to Indexable protocols
=> Optional Indexable

Sources/CodableDatastore/Datastore/Datastore.swift, Sources/CodableDatastore/Indexes/IndexRepresentation.swift
Added more sendable conformances.
=> More Sendable Conformances

Package.swift, Package@swift-6.0.swift, Sources/CodableDatastore/Indexes/UUID+Comparable.swift, Sources/CodableDatastore/Persistence/Disk Persistence/ISO8601DateFormatter+Milliseconds.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreIndexTests.swift, Tests/CodableDatastoreTests/DiskPersistenceDatastoreTests.swift, Tests/CodableDatastoreTests/DiskPersistenceTests.swift, Tests/CodableDatastoreTests/DiskTransactionTests.swift, Tests/CodableDatastoreTests/SnapshotTests.swift
Fixed Swift 6 support on linux now that it's been released.
=> Swift 6 Support
